### ISSUE TITLE
Method for detecting audio is completed or not and method for getting audio played percentage.

### ISSUE THREAD

**Issue by ibtisamniche-vteams** [vmudigal/ngx-audio-player#14]
@vmudigal Hi!
I have a project of learning management in which I made tutorials ( there are lessons in the tutorial ). Admin is uploading the audio in lesson and the student would listen that audio. I am going to enforce my students to listen full audio lesson before navigating to the next one so I need the feature to know if the audio is finished or not. If there would be the event that will be trigered on finishing the audio, that would handle my scenario. If the player emits percentage of audio being played that would be great as well.
Seeking for your reply.
Thanks.

**Comment by vmudigal** [comment]
Fixed and available in https://www.npmjs.com/package/ngx-audio-player/v/9.1.1
