### ISSUE TITLE
isn't a known property of 'mat-basic-audio-player'

### ISSUE THREAD

**Issue by SumitRajpal** [vmudigal/ngx-audio-player#19]
1. angular-fontawesome@0.3.0

I have installed all package but it still giving me error.

![Screenshot_1](https://user-images.githubusercontent.com/7436825/63692191-b6a79e80-c82e-11e9-9373-107f60315922.png)

**Comment by Babu1566** [comment]
**Please install this npm package**
npm install ngx-audio-player --save

**Add in your package.json file**
"@angular/material": "^8.0.0", 
"@fortawesome/angular-fontawesome": "^0.4.0", 
"@fortawesome/fontawesome-svg-core": "^1.2.19",
 "@fortawesome/free-solid-svg-icons": "^5.9.0"

**Comment by kryne** [comment]
I have same problem. Any solution?

**Comment by vmudigal** [comment]
@kryne Could you please add your code in stackbliz and share?

**Comment by vmudigal** [comment]
Obsolete
