### ISSUE TITLE
Fontawsome icons not showing in the audio player when updated to the last version

### ISSUE THREAD

**Issue by alfunso14** [vmudigal/ngx-audio-player#20]
I hided some buttons like forward button and backward button, and all was working fine, but when i updated the version of fontawsome to the last version 5, the icon not showing correctly, i tried updating and reinstalling ngx-audio-player, but didn't solve it, any help will be appreciated 

<img width="194" alt="Capture" src="https://user-images.githubusercontent.com/49029877/64790702-2d5ad080-d57f-11e9-85b3-fb07014cec15.PNG">

**Comment by Ant-Pinto** [comment]
@alfunso14 Did you ever figure this out?

**Comment by vmudigal** [comment]
Could you please try with ngx-audio-player@9.0.3?

**Comment by vmudigal** [comment]
Obselete.
