### ISSUE TITLE
TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by andrewsteier** [vmudigal/ngx-audio-player#23]
I'm building msaapPlaylist with array.push, but I get the cannot read property 'title' of undefined error.
If I leave the track hard coded like it is in the example, it works fine. (not gonna cut it)

**Comment by vmudigal** [comment]
@andrewsteier Could you please share the code? I am not able to replicate the issue.

Below example worked for me.
```
msaapPlaylist: Track[] = [];

constructor() {
     this.msaapPlaylist.push({
     title: '1400 (by Yung Kartz)',
      link: 'https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Yung_Kartz/August_2018/Yung_Kartz_-_10_-_1400.mp3'
    });
    this.msaapPlaylist.push({
      title: 'Epic Song (by BoxCat Games)',
      link: 'https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/BoxCat_Games/Nameless_The_Hackers_RPG_Soundtrack/BoxCat_Games_-_10_-_Epic_Song.mp3'
    });
    this.msaapPlaylist.push({
      title: 'Hachiko (The Faithful Dog) (by The Kyoto)',
      link: 'https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/The_Kyoto_Connection/Wake_Up/The_Kyoto_Connection_-_09_-_Hachiko_The_Faithtful_Dog.mp3'
    });
    this.msaapPlaylist.push({
      title: 'Starling (by Podington Bear)',
      link: 'https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Music_for_Video/Podington_Bear/Solo_Instruments/Podington_Bear_-_Starling.mp3'
    });
  }
```

**Comment by bbarn3y** [comment]
Hi,
I ran into the same error message, although it's possible that the cause is different.

I managed to reproduce, that in my case the error occurs when the last element of my playlist is selected, but then I remove the element before it from the playlist [the (n - 1)th element of the playlist].

Full stack trace:
![image](https://user-images.githubusercontent.com/8375284/76301884-54405800-62bf-11ea-9cc5-8b4485458f7c.png)

**Comment by naveen11** [comment]
is this issue resolved?

**Comment by vmudigal** [comment]
Obsolete in v9.1.1.

**Comment by naveen11** [comment]
I fixed this issue by changing below method..It's working with V8.0.3.
   
ngOnInit() {
        this.setDataSourceAttributes();
        this.bindPlayerEvent();
        this.player.nativeElement.addEventListener('ended', (/**
         * @return {?}
         */
            () => {
                if (this.checkIfSongHasStartedSinceAtleastTwoSeconds()) {
                    this.nextSong();
                }
            }));
        this.playlistService.setPlaylist(this.playlistData);
        this.playlistService.getSubjectCurrentTrack().subscribe((
        /**
         * @param {?} playlistTrack
         * @return {?}
         */
            (playlistTrack) => {
                this.playlistTrack = playlistTrack;
                if (this.playlistTrack) {
                    if (!this.playlistTrack[1]) {
                        if (this.playlistData != null) {
                             this.playlistTrack[1] = this.playlistData[0];
                        }
                    }
                } else if (this.playlistData != null) {
                    this.playlistTrack = this.playlistData[0];
                }

                if (typeof this.playlistTrack === "undefined") {
                    if (this.playlistData != null) {
                       this.playlistTrack = this.playlistData[0];
                    }
                }
            }));
        this.player.nativeElement.currentTime = 0;
        this.playlistService.init();
         if (this.autoPlay) {
             super.play();
         }
    }
