### ISSUE TITLE
The play button in the play list in the advanced view is not clickable

### ISSUE THREAD

**Issue by Arsenalist** [vmudigal/ngx-audio-player#3]

**Comment by vmudigal** [comment]
Hi Arsenalist, could you please explain the steps to reproduce the issue along with the environment details such as browser, operating systems etc? Thanks.

**Comment by Arsenalist** [comment]
If an audio clip is playing in a play list, the playlist list gets a play button next to the clip that's playing.  That play button I think should be clickable to pause/play.

**Comment by vmudigal** [comment]
The icon that appears next the to title in a playlist is meant to just indicate that track that is currently being played. Maybe the icon is bit confusing.
