### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by malibayram91** [vmudigal/ngx-audio-player#32]
Failed to compile.

./node_modules/ngx-audio-player/fesm2015/ngx-audio-player.js
Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome' in '/Users/user/angular/my-app/node_modules/ngx-audio-player/fesm2015'

**Comment by malibayram91** [comment]
please change  @fortawesome to @fontawesome
r => n

**Comment by vmudigal** [comment]
Its obselete.
