### ISSUE TITLE
Error during template compile of 'NgxAudioPlayerModule'   Could not resolve @fortawesome/angular-fontawesome relative to [object Object]..

### ISSUE THREAD

**Issue by kunjirsantosh** [vmudigal/ngx-audio-player#37]
This error comes after Angular 9 update. in angular 8 it was working fine.

ERROR in ngx-audio-player/ngx-audio-player.ts(27,40): Error during template compile of 'NgxAudioPlayerModule'
  Could not resolve @fortawesome/angular-fontawesome relative to [object Object]..

**Comment by vmudigal** [comment]
Could you please try using ngx-audio-player@9.0.3 and let me know if you still face this issue?

**Comment by kunjirsantosh** [comment]
This error is fixed @ ngx-audio-player@9.0.3
