### ISSUE TITLE
It would be great if i can get method that logs current time of the ngx-audio-player while playing

### ISSUE THREAD

**Issue by Pavan-Deepak** [vmudigal/ngx-audio-player#4]

**Comment by vmudigal** [comment]
Hi Pavan, but why would anyone need it? Could you please explain one scenario if you have thought about?

**Comment by Pavan-Deepak** [comment]
Hi Vmudigal,
I am using AWS polly Text to speech service and was able to integrate ngx audio player. But now i am integrating Speech mark  API while audio is playing it highlights the text in the textarea so i need a method that logs current time of audio so i can match the audio player current time  and speech mark time and highlight start and end char of the word.

**Comment by Doehl** [comment]
Hi Vmudigal,

I have the exact same use case as Pavan-Deepak.
But I can even think of a lot other use cases, where you need to actions based on timestamp.

**Comment by vmudigal** [comment]
Fixed in https://www.npmjs.com/package/ngx-audio-player/v/9.1.0 for mat-advanced-audio-player.  Will take care for mat-basic-audio-player soon.

**Comment by vmudigal** [comment]
Fixed and available in https://www.npmjs.com/package/ngx-audio-player/v/9.1.1
