### ISSUE TITLE
Affecting my project style.

### ISSUE THREAD

**Issue by hrosx** [vmudigal/ngx-audio-player#5]
How can I avoid the CSS CDN in this project is affecting my site style.

**Comment by camilocano146** [comment]
I have the same problem, the library add some styles to project, that styles issue my app.

**Comment by immersiontools** [comment]
Same problem ! Did you find a solution?

**Comment by bollerdominik** [comment]
+1 For not wanting to load in bootstrap and font awesome.

Hopping #27 will be merged eventually

**Comment by EdricChan03** [comment]
@bollerdominik Sorry for the long wait, but the spaghetti of code used for the component is too messy for me to fix in one small PR. The code has lots of troublesome issues, including:
* _Hardcoded_ styles (ugh)
* Unfinished tests
  * Tests using the wrong APIs altogether! (for e.g. using e2e-related infrastructure in component tests)
* Unfinished CI (continuous integration) system (currently only builds the project, nothing else)

And some other minor issues that need major refactoring, which require way more time than necessary to fix.

In the meantime, the only other thing you could do at the moment would be to create your own component or rely on another library altogether.

P.S. I've submitted an issue to the [Angular Components](https://github.com/angular/components) repository regarding an audio player (at angular/components#17513) but has been closed and locked (which was automatically done by their new infrastructure - a GitHub Action workflow - which automatically locks issues/PRs that are stale) as they "don't have any plans to build any kind of audio/video components".

Hope this helps!

**Comment by vmudigal** [comment]
Fixed in https://www.npmjs.com/package/ngx-audio-player/v/10.1.0
