### ISSUE TITLE
Ended event not exposed

### ISSUE THREAD

**Issue by johanchouquet** [vmudigal/ngx-audio-player#52]
Hi there,

This is a feature request.

First, thank you for this library!

I'd like to be able to use the "ended" event at the end of a basic audio stream, like in:

[Ended event](https://developer.mozilla.org/fr/docs/Web/API/HTMLMediaElement/ended_event)
[Can i Use](https://caniuse.com/#feat=mdn-api_htmlmediaelement_ended)

The API the library provides doesn't seem to expose this one.

Would be great to be able to have this event as an output.

**Comment by vmudigal** [comment]
Fixed the issue in https://github.com/vmudigal/ngx-audio-player/commit/93ef04e9e0cf722256357269b4a08303b47fe025.
Fix available in https://www.npmjs.com/package/ngx-audio-player/v/9.0.7
