### ISSUE TITLE
More Than One Advanced Player Per Page

### ISSUE THREAD

**Issue by ewwwgiddings** [vmudigal/ngx-audio-player#54]
I am getting an error when I have two instances of mat-advanced-audio-player per page. When one gets loaded after another one, the first one's data such as Title and Link get over rode.

Any idea why this would happen, or how to fix it?

**Comment by ewwwgiddings** [comment]
The title's inside the expanded playlist don't get changed. It's only on the player and player's title where things get changed to the latest loaded.

Is it pointing to a global variable? If so, any way to point it more locally so more than one instance can be loaded on a page?

**Comment by vmudigal** [comment]
That's a know limitation of this library. Won't be taking it in the near future.

**Comment by ewwwgiddings** [comment]
It would be nice to have that stated in the README.

I started to use Plyr in place of the audio portion and built my own similar layout instead of this library for this reason.

It would be nice to state that on the README so people know limitations up front.
