### ISSUE TITLE
Property 'onEnded' does not exist on type 'AppComponent'.

### ISSUE THREAD

**Issue by sanjay-devappsys** [vmudigal/ngx-audio-player#57]
In angular 9 i'm having this issue

**Comment by vmudigal** [comment]
@sanjay-devappsys, could you please share the code?

**Comment by sanjay-devappsys** [comment]
Actually I just copy pasted the advanced option which you've written in the repo readme file, and I think the issue is because of the binding in `(ended )="onEnded($event)` attribute. 
The compiler in the angular 9 has been updated, usually in angular 8 or lesser this error would have appeared while we `building`  the project. Anyway I was able to get rid of the error by adding an empty `onEnded` function in the corresponding component.
