### ISSUE TITLE
After ng build --prod process, I got this.bindPlayEvent is not a function error

### ISSUE THREAD

**Issue by SeoBoSeok** [vmudigal/ngx-audio-player#6]
Wonderful audio player for ng7+
But I got some errors after finishing build --prod then,

this.bindPlayerEvent is not a function
at e.ngOnInit ........

How can I fix this issue?

**Comment by SeoBoSeok** [comment]
> Wonderful audio player for ng7+
> But I got some errors after finishing build --prod then,
> 
> this.bindPlayerEvent is not a function
> at e.ngOnInit ........
> 
> How can I fix this issue?

I just remove all package and reinstall and build again~!!
All errors has gone.

But, Now I got new error in this time.
I check mobile device and figure out player is something wrong.

Is this module not support for mobile web browser?

**Comment by vmudigal** [comment]
It should support mobile web browser as well as its responsive in nature.
