### ISSUE TITLE
ngx-audio-player styles

### ISSUE THREAD

**Issue by dm-grinko** [vmudigal/ngx-audio-player#64]
The player is working but there is no styles. The documentation is horrible. 

https://monosnap.com/file/LvHvhphA0Sck570ZzCGPzsIVg81LAv

**Comment by vmudigal** [comment]
Hi @dm-grinko,

Please feel free to refer an example from the Stackblitz URL below, 

https://stackblitz.com/edit/ngx-audio-player-v9-advanced

Could you please let me know your thoughts on what contents could be included in the documentation and how could it be structured to perfect so it's easy to refer. 

Thanks,
VJ

**Comment by ghill7777** [comment]
I had purple-green instead of deeppurple-amber for the material style.  None of the control buttons / mat-icons showed until I switched to deeppurple.  The icons were white on a white background.. FYI

**Comment by vmudigal** [comment]
Fixed in https://www.npmjs.com/package/ngx-audio-player/v/10.1.0
