### ISSUE TITLE
Get current played title

### ISSUE THREAD

**Issue by keschra** [vmudigal/ngx-audio-player#65]
Is it possible to get the current played song of the player? I want to add an image above the player but it should switch when another song is played. I could not find out how to get the current song.

**Comment by vmudigal** [comment]
As of today, the mat-advanced-audio-player supports this functionality if ngx-audio-player version is more than 9.1.0.

You could achieve this by the code below,

```
  currentTrack: Track = null;
  constructor(private audioPlayerService: AudioPlayerService) {}
 
  logCurrentTrack() {
    this.audioPlayerService.getCurrentTrack().subscribe(track => {
      this.currentTrack = track;
    });
  }
```

**Comment by keschra** [comment]
Thank you! This should work. Can you add the service to the public_api? At the moment i cant import the service to my project.

**Comment by vmudigal** [comment]
Hi @keschra, 

It is available in 9.1.0.
https://github.com/vmudigal/ngx-audio-player/blob/9.x.x/projects/ngx-audio-player/src/public_api.ts

Thanks.

Best Regards,
Vijayendra

**Comment by vmudigal** [comment]
With version 9.1.1 you could refer the audioPlayerService from the component.

**Comment by keschra** [comment]
@vmudigal since the update to 9.1.1 it is not working anymore. Version 9.1.0 was working

**Comment by vmudigal** [comment]
@keschra , The working demo is publish at https://vmudigal.github.io/ngx-audio-player/.

It must be an issue with the setup, could you please refer the demo code while I work on the documentation for all of the features provided by the library.

**Comment by vmudigal** [comment]
@keschra , If you could share the code in stackblitz, I could help you fix the issues with the setup. Thanks.

**Comment by keschra** [comment]
@vmudigal  where can i view the demo code? I can't find the code of the working demo. 
by the way, many thanks for the good support!

**Comment by vmudigal** [comment]
@keschra what you see at  https://vmudigal.github.io/ngx-audio-player/ is from the code at https://github.com/vmudigal/ngx-audio-player/tree/master/src/app/home. Please look at home.component.html and home.component.ts.

Please feel to let me know incase of any concerns.
