### ISSUE TITLE
Feature request: Auto-replay option

### ISSUE THREAD

**Issue by Abdullah0991** [vmudigal/ngx-audio-player#68]
Hi,

I know I can use the `trackEnded` event for auto-replay the track, but It will be more beautiful if this option added to the library, especially if you could also add a `button toggle` or `checkbox` control to control this option from the UI, the `toggle button` could be added besides the volume mute button.

Regards.

**Comment by vmudigal** [comment]
duplicate of Auto Play Error #58

**Comment by Abdullah0991** [comment]
Sorry, but what's the link between auto-**replay** and auto-**play** ?

**Comment by vmudigal** [comment]
My bad, read it wrong. Sorry.

**Comment by vmudigal** [comment]
Duplicate of Repeat/Loop function #47
