### ISSUE TITLE
how to enable the automatic playback of the next song in the playlist?

### ISSUE THREAD

**Issue by guitargfv** [vmudigal/ngx-audio-player#72]
My playlist does not automatically play the next song after the end of the previous one. Any tips?

**Comment by dm-grinko** [comment]
play(item: any) {
    this.msbapTitle = item.title;
    this.msbapAudioUrl = item.url;
    const player = document.querySelectorAll('audio')[0];
    setTimeout(() => {
      player.play();
    }, 1000);
  }

**Comment by vmudigal** [comment]
The regression has been taken care from v8 and above.
