### ISSUE TITLE
Allow internationalization of fixed texts

### ISSUE THREAD

**Issue by guitargfv** [vmudigal/ngx-audio-player#73]
As a suggestion, you could allow the internationalization of fixed texts such as:
  - "Items per page"
  - "Playlist"
  - "Tile"
Making values dynamic would also be interesting

**Comment by vmudigal** [comment]
Except "Play List" and "Title" (will work on it), everything else such as "Items per page", "1 – 2 of 4", "Next Page", "Last Page", "Previous Page", "First Page" is taken care by MatPaginatorIntl.

Please refer below:
https://stackoverflow.com/questions/47593692/how-to-translate-mat-paginator-in-angular-4

**Comment by vmudigal** [comment]
Available in https://www.npmjs.com/package/ngx-audio-player/v/10.1.0
