### ISSUE TITLE
Enhancement Request: Volume control

### ISSUE THREAD

**Issue by dmbrenneman** [vmudigal/ngx-audio-player#8]
It would be great if the basic player had some form of volume control for users to interact with.

**Comment by vmudigal** [comment]
The basic player and advanced player now has the volume control to mute/unmute as show in the image below.

Basic Player:

![alt text](https://github.com/vmudigal/ngx-audio-player/blob/master/docs/images/basic-player.png?raw=true)

Advanced Player:

![alt text](https://github.com/vmudigal/ngx-audio-player/blob/master/docs/images/advanced-player.png?raw=true)

**Comment by dmbrenneman** [comment]
Great....however, it would be preferable to allow the user to control the volume level rather than just mute/unmute.

**Comment by vmudigal** [comment]
I initially thought of the same. But unfortunately, that does not go well
with the mobile browsers.

**Comment by dmbrenneman** [comment]
Right, that does present a challenge. What about conditional logic to disable the feature for mobile devices using some kind of function for checking the userAgent?

**Comment by vmudigal** [comment]
That's not a problem, but won't be consistent across web and mobile.
Compare few sites like amazon music. The native mobile app does not have
volume controls.

Let me know if it makes a huge difference.
