### ISSUE TITLE
Since new 10.0.0 version triggers BrowserModule issue

### ISSUE THREAD

**Issue by Zokor** [vmudigal/ngx-audio-player#83]
Hi,

This component is throwing

ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

Since BrowserAnimationsModule is something that should be declared at the app.module (it's usually required by other components), you guys should remove it from the shipped code and add a reference for people to add it to the app.module.

Thank you for this work on this repo of yours :)

Best regards

**Comment by aalexop** [comment]
Any solution for this issue?

**Comment by Zokor** [comment]
You can remove the references from your current Node Modules to the BrowserModule of the ngx-audio-player.

But if they update this it would be better.

**Comment by 6utt3rfly** [comment]
PR #86 - I'm using it with by putting the github link in my package.json file:
```json
"ngx-audio-player": "https://github.com/betastreet/ngx-audio-player/archive/build.tar.gz"
```

**Comment by vmudigal** [comment]
Sorry for the delay as I was occupied. The latest versions have the fix.

v8.1.1, v9.2.0 and v10.1.1
