### ISSUE TITLE
Package "ngx-audio-player" has an incompatible peer dependency to "@angular/material" (requires "^10.0.0", would install "11.0.3").

### ISSUE THREAD

**Issue by Zokor** [vmudigal/ngx-audio-player#96]
Hi m8,

Thank you for your work :)

Is it possivel if you bump the version to the latest angular material?

Cheers

**Comment by vmudigal** [comment]
Hi @Zokor, are you using [ngx-audio-player@v11.0.2](https://www.npmjs.com/package/ngx-audio-player/v/11.0.2)?

**Comment by Zokor** [comment]
Oh, i'm sorry man. It's fine! :) let me close this
