### ISSUE TITLE
Play single audio file without repeating

### ISSUE THREAD

**Issue by get2abhi** [vmudigal/ngx-audio-player#97]
I used only 1 item in the array and the player worked fine however the audio is getting played in a loop. I used the trackEnded callback but couldn't find a way to stop the player.

**Comment by pulkitpatel95** [comment]
how to get instance of audio player and is there any method to stop audio ?

**Comment by pulkitpatel95** [comment]
> I used only 1 item in the array and the player worked fine however the audio is getting played in a loop. I used the trackEnded callback but couldn't find a way to stop the player.

You can empty the track array on trackEnded callback. (You can push the track in array again if you want to see it on page)

sample 

onEnded($event): void {
    this.msaapPlaylist = [];
    this.msaapPlaylist.push({
      title: 'Play One Track Only',
      // link: '../../assets/audios/005_30_second.mp3',
      link: 'https://www.w3schools.com/html/horse.ogg',
      artist: 'Pulkit',
    });
  }

**Comment by get2abhi** [comment]
Thanks. that worked

**Comment by vmudigal** [comment]
Feature available in v8.1.4, v9.2.3, v10.1.4 and v11.0.4.
